removing fuel when not supported
telosnetwork/telos-wallet pull request #135
Opened 2023-02-14 01:26 UTC by Viterbo

# Fixes #134

## Description
The fuel service is working as expected in the chains that are supported but are introducing problems in the not supported ones. This PR fixes the problem.

## Test scenarios
- Login to testnet
- open the browser inspector and enter tab Network
- modify filters, select: Fetch/XHR
- try to sign any transaction (send tokens, stake or unstake)
- You should not see a POST request like this: https://telos.greymass.com/v1/resource_provider/request_transaction
- You should be able to perform the signing as regularly (without fuel)

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages

2023-02-15 18:09 UTC, EJSG approved these changes

2023-02-15 18:57 UTC, karynemayer requested changes

2023-02-15 18:57 UTC, karynemayer commented on env.js
> +console.log("----------------------------------");
could you remove this?

2023-02-17 19:18 UTC, karynemayer approved these changes

2023-02-17 19:41 UTC, merged