Can't send non-system tokens
telosnetwork/telos-wallet pull request #370
Opened 2023-05-30 20:36 UTC by donnyquixotic

# Fixes #337

## Description
Fixes issues sending non-system tokens

## Test scenarios
- Login and send non-system token (WTLOS, STLOS, <other>)

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file
-   [ ] I have created a new issue with the required translations for the currently supported languages
-   [ ] I have added appropriate test coverage

2023-05-30 20:51 UTC, EJSG requested changes
still unable to send WTLOS

![image](https://github.com/telosnetwork/telos-wallet/assets/11837820/d85634fe-2a3c-4f5c-a7d7-60c2172b11eb)

2023-05-30 20:51 UTC, EJSG commented
maybe its related to, like Jesse said, WTLOS is not verified on testnet? but we should still be able to send it

2023-05-30 22:27 UTC, donnyquixotic commented
> maybe its related to, like Jesse said, WTLOS is not verified on testnet? but we should still be able to send it

it was missing creation data that was causing an error, verification shouldn't matter.

2023-05-31 00:44 UTC, pmjanus approved these changes

2023-05-31 16:07 UTC, merged