adding isMainnet function to chain settings
telosnetwork/telos-wallet pull request #375
Opened 2023-05-31 14:09 UTC by Viterbo

## Description
This PR was created to fix #374 but it turned out to be a misunderstanding. #374 is not a bug, in fact, you can see it works on real production https://wallet.telos.net/

What this PR does though is add a new isMainnet function in the settings of each chain to answer that question.

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages

2023-05-31 16:27 UTC, donnyquixotic requested changes
@Viterbo let's talk about this.

2023-05-31 19:03 UTC, donnyquixotic approved these changes

2023-06-01 17:29 UTC, EJSG commented
added a new issue to investigate this too https://github.com/telosnetwork/telos-wallet/issues/388

2023-06-01 17:29 UTC, EJSG approved these changes

2023-06-08 18:03 UTC, Viterbo commented
There's no sense for this PR to be merged. At least, not for now since it adds nothing really useful. So I close this PR.

2023-06-08 18:03 UTC, closed without merging