refactoring balance update
telosnetwork/telos-wallet pull request #433
Opened 2023-06-21 03:07 UTC by Viterbo

# Fixes #429

## Description
The balance update was not working as expected for empty accounts so I take this opportunity to refactor all the balance update strategies for a cleaner and easy-to-understand code.

## Test scenarios

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

2023-06-22 21:12 UTC, ezra-guzman approved these changes
👏 very nice refactor

2023-06-24 00:30 UTC, donnyquixotic commented
- When connected to an account with only TLOS, the STLOS and WTLOS do not display:
![image](https://github.com/telosnetwork/telos-wallet/assets/6848910/61c589aa-a1e2-4e9a-95ae-c21a4f744ac7)

2023-06-24 00:37 UTC, donnyquixotic requested changes
Missing WTLOS and STLOS for account with _only_ TLOS. 
![image](https://github.com/telosnetwork/telos-wallet/assets/6848910/61c589aa-a1e2-4e9a-95ae-c21a4f744ac7)

2023-06-27 18:01 UTC, donnyquixotic approved these changes

2023-06-27 18:01 UTC, merged