#350 | TX table improvements
telosnetwork/telos-wallet pull request #455
Opened 2023-06-30 22:43 UTC by ezra-guzman

# Fixes #350 

## Description
This PR does 2 things:
- prefetch transactions if you are on the wallet balance page
- re-fetch transactions every 13 seconds if you are on the first page (does not refetch if on other pages to prevent data from randomly shifting around for the user)

## Test scenarios
- 

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

2023-07-03 00:19 UTC, pmjanus commented
JP, [Jul 2, 2023 at 7:19:06 PM]:
Telos Web Wallet
A Web Wallet for Telos

JP, [Jul 2, 2023 at 7:19:06 PM]:
app.31cebd94.js:1 Indexer API not working for this chain: telos-evm Error: Network Error
    at e.exports (vendor.d0a3678c.js:113:10579)
    at b.onerror (vendor.d0a3678c.js:113:6240)
(anonymous) @ app.31cebd94.js:1
content.js:69  while testing : https://deploy-preview-455--wallet-staging.netlify.app/evm/wallet?tab=transactions
sent myself a token it never updated

Also this error: inpage.js:8 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 "disconnect" listeners added. Use emitter.setMaxListeners() to increase limit.

2023-07-05 20:15 UTC, donnyquixotic requested changes
I'm getting a 500 error on both Desktop and Mobile:
`Uncaught (in promise) Error: antelope.history.error_fetching_transactions
    at Proxy.fetchEVMTransactionsForAccount (history.ts:129:1)`
![image](https://github.com/telosnetwork/telos-wallet/assets/6848910/532388c1-c32d-49cb-9e08-a7debad578bc)

2023-07-06 19:35 UTC, Viterbo approved these changes
Nice & Clean. GJ!

2023-07-06 20:10 UTC, Viterbo commented
> I'm getting a 500 error on both Desktop and Mobile (results in loading screen -> no transactions fetched): `Uncaught (in promise) Error: antelope.history.error_fetching_transactions at Proxy.fetchEVMTransactionsForAccount (history.ts:129:1)` ![image](https://user-images.githubusercontent.com/6848910/251271471-532388c1-c32d-49cb-9e08-a7debad578bc.png)

I take this one since EZ is on vacation from today. 

I did push some code to handle that error, show a notification and stop iteration from continuing fetching.
![Captura desde 2023-07-06 17-04-57](https://github.com/telosnetwork/telos-wallet/assets/4420760/feecc0ed-b887-4fed-8340-46260af3eead)

2023-07-06 20:38 UTC, merged