Authenticate user with social media
telosnetwork/telos-wallet pull request #490
Opened 2023-07-20 04:16 UTC by Viterbo

# Fixes #463

## Description
This PR includes a new button for the Home page (on the EVM side) which provides the users a way to authenticate using social media providers without even having a wallet installed.

## Test scenarios

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

2023-07-21 21:17 UTC, ezra-guzman approved these changes
works very well for me on desktop and mobile, awesome job 💯

2023-07-26 19:28 UTC, donnyquixotic requested changes
EDIT: this is for mainnet, testnet is working as expected. We should update the official app ids for both as part of this PR

I'm receiving a zero balance error preventing send transaction (account has available TLOS) using google via oreid:
![image](https://github.com/telosnetwork/telos-wallet/assets/6848910/40c5a597-1502-4acb-b82e-d3099625825b)

2023-07-26 19:58 UTC, donnyquixotic approved these changes

2023-07-26 20:04 UTC, donnyquixotic commented
- [ ] update appId (testnet)
- [ ] update appId (mainnet)

2023-07-28 16:14 UTC, Viterbo commented
Re-opening this PR that I think was closed by mistake

2023-07-28 18:26 UTC, donnyquixotic approved these changes

2023-07-28 18:26 UTC, merged

2023-07-28 18:27 UTC, Viterbo commented on src/antelope/wallets/authenticators/OreIdAuth.ts
> +            chainNetwork: this.getChainNetwork(useChainStore().getChain(this.label).settings.getNetwork()),
Nice !!! :+1: