#602 | Initial allowances page
telosnetwork/telos-wallet pull request #632
Opened 2023-10-06 23:05 UTC by ezra-sg

# Fixes #602

## Description
This PR adds the page and control elements for allowances

## Test scenarios
- `git fetch --all && git checkout 602-allowances-layout && yarn dev`
- go to http://localhost:8081
- log in
    - you should see a new allowances menu item
- go to allowances page
    - it should match the designs (some text has been changed)

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

2023-10-09 22:23 UTC, Viterbo approved these changes
This is coming good :+1: 
Approved!

2023-10-16 15:02 UTC, donnyquixotic requested changes

2023-10-16 15:02 UTC, donnyquixotic commented on bun.lockb
Did you intend to include this?

2023-10-16 20:00 UTC, donnyquixotic approved these changes

2023-10-16 20:06 UTC, merged