606 revoke allowances api integration
telosnetwork/telos-wallet pull request #717
Opened 2023-12-15 23:38 UTC by ezra-sg

# Fixes #issue_number

## Description

## Test scenarios

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

2023-12-23 00:59 UTC, donnyquixotic requested changes
Great job on this!!! Minor modal copy suggestions.

2023-12-23 00:59 UTC, donnyquixotic commented on src/i18n/en-us/index.js
> +        revoking_allowances_cancel_note: 'Note: clicking Cancel will not cancel transactions which have already been approved. After clicking Cancel, you may also need to cancel the current transacti
```suggestion
        revoking_allowances_cancel_note: 'Note: clicking 'Cancel' will not cancel transactions which have already been approved. Any pending transaction(s) must be cancelled in your wallet.',
```

2023-12-23 00:59 UTC, donnyquixotic commented on src/i18n/en-us/index.js
> +        revoking_allowances_description: 'Please wait while we revoke the selected allowances; this may take up to 10 minutes. You will need to approve the transactions in your wallet as they come up
```suggestion
        revoking_allowances_description: 'Please wait while we revoke the selected allowances. You will need to approve each transaction in your wallet.',
```

2023-12-24 18:25 UTC, Viterbo approved these changes
"Me saco el sombrero" :tophat: 

The only detail I noticed is that if you have a batch of revokes to process, cancelling the operation causes you to lose the selection you had. That is a colateral effect of reseting all checkboxes when the data changes. To fix this problem you would probably need to allow initial selection from the outside of the component which is an overkill solution. So let it as it is... 

Good Job !!

2023-12-26 15:50 UTC, donnyquixotic approved these changes

2023-12-26 18:11 UTC, merged