44 feature request fix header on coin table
telosnetwork/telos-wallet pull request #72
Opened 2022-12-08 22:45 UTC by Viterbo

# Fixes #44

## Description
If the list of tokens gets too big the user may end up scrolling all the headers out of the screen and that is not desirable. To fix this, some refactoring was needed (and it's needed a lot more) and the max height of the table was fixed to a maximum height, such that the table headers are always inside the screen.

## Test scenarios
- hight and low resolutions
- with many tokens and with just a few

# Sreenshots

![image](https://user-images.githubusercontent.com/4420760/206582430-54832bf4-f908-446e-8753-c7187a9a948e.png)

![image](https://user-images.githubusercontent.com/4420760/206582717-4571a967-6518-42f1-a80c-cef384dbec73.png)

![image](https://user-images.githubusercontent.com/4420760/206582517-3c37935c-90f2-4bc0-8fe0-791d1d97d67b.png)

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages

2022-12-09 01:41 UTC, karynemayer requested changes
My only improvement point would be that the style of the scrollbar. The screenshot shows the scrollbar I'm looking at, which is what I hoped to see on your screenshots. If this is not what it looks for you, I would suggest that we define the css for the srollbar to look more similar to the screenshot. 

<img width="803" alt="Screen Shot 2022-12-08 at 17 33 03" src="https://user-images.githubusercontent.com/2939354/206603105-4db62393-c47c-44bf-acf3-ae642ed984a6.png">

[Here](https://gist.github.com/spemer/a0e218bbb45433bd611e68446523a00b) is an example of what I mean.

2022-12-11 19:54 UTC, donnyquixotic approved these changes

2022-12-15 16:42 UTC, Viterbo commented
![image](https://user-images.githubusercontent.com/4420760/207917914-24c2f83a-9096-494b-ae9e-c777d976d76a.png)

2022-12-15 17:14 UTC, donnyquixotic approved these changes

2022-12-15 17:15 UTC, merged