[No ticket] | Add empty allowances state
telosnetwork/telos-wallet pull request #749
Opened 2024-01-11 22:58 UTC by ezra-sg

## Description
This PR adds an empty state for the allowance page

## Test scenarios
- go to
- sign in with an account which has approvals (e.g. team account)
- go to approvals page
    - page should be unchanged
- switch account to one with no approvals
    -  you should see an empty state

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

2024-01-12 03:30 UTC, donnyquixotic approved these changes

2024-01-13 03:23 UTC, pmjanus requested changes
Added issue with changes requested https://github.com/telosnetwork/telos-wallet/issues/750

2024-01-15 13:19 UTC, Viterbo submitted a review, later dismissed
Approved

2024-01-29 18:19 UTC, donnyquixotic approved these changes

2024-01-29 18:19 UTC, merged