auto-close dialog when no access to the camera
telosnetwork/telos-wallet pull request #93
Opened 2023-01-02 06:47 UTC by Viterbo

# Fixes #29 

## Description
The dialog did not react to the denial of access to the camera remaining open and useless. The user had to refresh to come back to the balances page. This PR fixes that idle behavior by closing the dialog when non-access to the camera is detected, showing to the user an appropriate notification message.

## Test notes
To test this new behavior you need to follow these steps:
- clean any pre-set configuration to access the camera (forget your previous answer)
- Click on the QR button (center between **Send** and **Receive** buttons)
- A dialog opens with a loading spinner (this is new)
- A browser dialog prompts if you allow the site to access the camera.
- Click on Deny.
- The dialog should close automatically and an error message should be shown asking for approval.

##screenshots

![image](https://user-images.githubusercontent.com/4420760/210201390-05524c9b-efa4-4d32-99ab-597b126a13dd.png)

![image](https://user-images.githubusercontent.com/4420760/210201096-093cd246-a414-4462-8d7d-eeef35a753f4.png)

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages

2023-01-02 18:42 UTC, EJSG commented on src/pages/components/balance/QRScanner.vue
> +        setTimeout(async () => { this.activateQR = true; }, 250);
arrow function doesn't need to be `async` as it has no async code

2023-01-02 18:42 UTC, EJSG approved these changes
looks good, i like the different error messages :+1: left an optional comment

2023-01-02 19:48 UTC, donnyquixotic approved these changes

2023-01-03 22:13 UTC, karynemayer requested changes
`yarn.lock` should not be deleted

2023-01-05 22:26 UTC, donnyquixotic approved these changes

2023-01-05 22:28 UTC, merged